name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        docker build . -f Dockerfile -t my-image-name:$(date +%s)
        docker tag my-image-name:$(date +%s) my-image-name:latest

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: docker push my-image-name:latest

    - name: Deploy to Production
      run: |
        node index.js
      env:
        NODE_ENV: production
      if: github.ref == 'refs/heads/main'
